/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package listaDeTarefas.view;

import java.sql.Connection;
import listaDeTarefas.model.ConexaoSQLite;

/**
 *
 * @author FELIPECANTINI
 */
public class UpdateView extends javax.swing.JFrame {

    /**
     * Creates new form UpdateView
     */
    
    ConexaoSQLite conexaoSQLite = new ConexaoSQLite();
    
    Connection conexao = conexaoSQLite.conectar();
    
    
    public UpdateView(String id, String titulo, String descricao, String dataVencimento) {
        
        initComponents();
        novoTitulo.setText(titulo);
        novaDescricao.setText(descricao);
        novaData.setText(dataVencimento);
        idTarefa.setText(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        painelUpdate = new javax.swing.JPanel();
        checkConcluido = new javax.swing.JCheckBox();
        novoTitulo = new javax.swing.JTextField();
        novaDescricao = new javax.swing.JTextField();
        novaData = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idTarefa = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Californian FB", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lista de Tarefas");

        jLabel5.setFont(new java.awt.Font("Californian FB", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lista de Tarefas");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelUpdate.setBackground(new java.awt.Color(28, 15, 94));

        checkConcluido.setBackground(new java.awt.Color(26, 15, 94));
        checkConcluido.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        checkConcluido.setForeground(new java.awt.Color(255, 255, 255));
        checkConcluido.setText("Concluir");
        checkConcluido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkConcluidoActionPerformed(evt);
            }
        });

        novoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoTituloActionPerformed(evt);
            }
        });

        novaDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaDescricaoActionPerformed(evt);
            }
        });

        novaData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaDataActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Titulo");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descrição");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data");

        idTarefa.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        idTarefa.setForeground(new java.awt.Color(255, 255, 255));
        idTarefa.setText("\"");

        javax.swing.GroupLayout painelUpdateLayout = new javax.swing.GroupLayout(painelUpdate);
        painelUpdate.setLayout(painelUpdateLayout);
        painelUpdateLayout.setHorizontalGroup(
            painelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelUpdateLayout.createSequentialGroup()
                .addGroup(painelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelUpdateLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(painelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(painelUpdateLayout.createSequentialGroup()
                                .addComponent(checkConcluido, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnAtualizar))
                            .addComponent(novaData, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(novaDescricao, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(novoTitulo, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(painelUpdateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(idTarefa)))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        painelUpdateLayout.setVerticalGroup(
            painelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelUpdateLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(novoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(novaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(novaData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkConcluido, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar))
                .addGap(38, 38, 38)
                .addComponent(idTarefa)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkConcluidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkConcluidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkConcluidoActionPerformed

    private void novoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoTituloActionPerformed

    private void novaDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novaDescricaoActionPerformed

    private void novaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novaDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateView("id", "titulo", "descricao", "dataVencimento").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JCheckBox checkConcluido;
    private javax.swing.JLabel idTarefa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField novaData;
    private javax.swing.JTextField novaDescricao;
    private javax.swing.JTextField novoTitulo;
    private javax.swing.JPanel painelUpdate;
    // End of variables declaration//GEN-END:variables
}
