/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package listaDeTarefas;

import java.sql.Connection;
import listaDeTarefas.model.ConexaoSQLite;
import listaDeTarefas.model.CriarTabela;
import listaDeTarefas.view.MainView;

public class App {

    public static void main(String[] args) {
        
        Connection conexao = ConexaoSQLite.conectar();
        
        CriarTabela.criarTabelaTarefas(conexao);
        
       new MainView().setVisible(true);
    }
}
